"use client";

import { useEffect, useState } from "react";
import { Activity, Building2, CheckCircle2, Eye, KeyRound, RefreshCw, ShieldCheck, SlidersHorizontal, UserRound, X } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import PlatformCommandCenter from "@/components/PlatformCommandCenter";

type Tenant = { id: number; name: string; status: "active" | "suspended"; plan_status: "trial" | "active" | "suspended"; subscription_plan?: "free" | "pro" | "enterprise"; admin_email: string | null; user_count: number; max_users: number; max_warehouses: number; created_at: string; };
type AuditLog = { id: number; action: string; target_type: string; target_id: string | null; created_at: string; };
type Dashboard = { tenants: Tenant[]; plans: { id: string; name: string; monthly_price: number; feature_flags: Record<string, boolean> }[]; maintenance: boolean; metrics: { activeTenants: number; mrr: number; totalUsers: number; transactionVolume: number; systemHealth: string }; auditLogs: AuditLog[]; error?: string };

const copy = {
  en: { eyebrow: "StoreFlow platform control", title: "Super Admin", intro: "Global tenant operations, platform health, and support access.", refresh: "Refresh", active: "Active companies", mrr: "Monthly platform revenue", users: "Total system users", health: "System health", healthy: "Operational", tenants: "Tenant control", workspace: "Workspace", admin: "Admin email", plan: "Plan", limits: "Users / warehouses", created: "Created", actions: "Actions", suspend: "Suspend", unsuspend: "Unsuspend", changePlan: "Change plan", edit: "Edit limits", reset: "Reset password", view: "Impersonate", audit: "System audit log", noAudit: "No platform changes recorded yet.", close: "Close", save: "Save limits", cancel: "Cancel", temporary: "Temporary password", copy: "Copy", copied: "Copied", support: "Support session expires in 30 minutes", trial: "Trial", activePlan: "Active", suspended: "Suspended", loading: "Loading platform data...", denied: "Unable to load platform data.", plans: "Subscription & revenue", operations: "Platform operations", provision: "Manual provisioning", maintenance: "Global maintenance mode", maintenanceOn: "Enable maintenance", maintenanceOff: "Disable maintenance", maintenanceHint: "Lock non-platform traffic during migrations.", planFeatures: "Feature flags", price: "Monthly price", company: "Company", fullName: "Owner name", email: "Owner email", password: "Temporary password", provisionNow: "Provision company", promo: "Promo extension", days: "Extension days", note: "Internal note", grant: "Grant extension", free: "Free", pro: "Pro", enterprise: "Enterprise" },
  ar: { eyebrow: "تحكم منصة StoreFlow", title: "مدير النظام", intro: "إدارة المستأجرين وصحة المنصة ودعم العملاء.", refresh: "تحديث", active: "الشركات النشطة", mrr: "إيرادات المنصة الشهرية", users: "إجمالي مستخدمي النظام", health: "صحة النظام", healthy: "تعمل بشكل طبيعي", tenants: "إدارة المستأجرين", workspace: "مساحة العمل", admin: "بريد المسؤول", plan: "الخطة", limits: "المستخدمون / المستودعات", created: "تاريخ الإنشاء", actions: "الإجراءات", suspend: "تعليق", unsuspend: "إلغاء التعليق", changePlan: "تغيير الخطة", edit: "تعديل الحدود", reset: "إعادة تعيين كلمة المرور", view: "انتحال الهوية", audit: "سجل تدقيق النظام", noAudit: "لا توجد تغييرات مسجلة بعد.", close: "إغلاق", save: "حفظ الحدود", cancel: "إلغاء", temporary: "كلمة المرور المؤقتة", copy: "نسخ", copied: "تم النسخ", support: "تنتهي جلسة الدعم خلال 30 دقيقة", trial: "تجريبية", activePlan: "نشطة", suspended: "معلقة", loading: "جار تحميل بيانات المنصة...", denied: "تعذر تحميل بيانات المنصة.", plans: "الاشتراكات والإيرادات", operations: "عمليات المنصة", provision: "إنشاء شركة يدويًا", maintenance: "وضع الصيانة العام", maintenanceOn: "تفعيل الصيانة", maintenanceOff: "إيقاف الصيانة", maintenanceHint: "قفل المستخدمين أثناء الترحيلات.", planFeatures: "أعلام الميزات", price: "السعر الشهري", company: "الشركة", fullName: "اسم المالك", email: "بريد المالك", password: "كلمة مرور مؤقتة", provisionNow: "إنشاء الشركة", promo: "تمديد ترويجي", days: "أيام التمديد", note: "ملاحظة داخلية", grant: "منح التمديد", free: "مجانية", pro: "احترافية", enterprise: "مؤسسات" },
};

function date(value: string, locale: string) { return new Intl.DateTimeFormat(locale, { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
function money(value: number, locale: string) { return new Intl.NumberFormat(locale, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }

export default function SuperAdminPage() {
  const { locale, dir } = useI18n();
  const text = copy[locale];
  const [data, setData] = useState<Dashboard | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState<Tenant | null>(null);
  const [password, setPassword] = useState<string | null>(null);

  async function load() {
    setBusy(true); setError(null);
    try { const response = await fetch("/api/super-admin", { cache: "no-store" }); const body = await response.json().catch(() => null) as (Dashboard & { error?: string }) | null; if (!response.ok) throw new Error(body?.error ?? text.denied); if (!body) throw new Error(text.denied); setData(body); } catch (reason) { setError(reason instanceof Error ? reason.message : text.denied); } finally { setBusy(false); }
  }
  useEffect(() => { load(); }, []);

  async function mutate(body: Record<string, unknown>) {
    const response = await fetch("/api/super-admin", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json().catch(() => null) as { error?: string; temporaryPassword?: string } | null;
    if (!result) { setError(text.denied); return; }
    if (!response.ok) { setError(result.error ?? text.denied); return; }
    if (result.temporaryPassword) setPassword(result.temporaryPassword);
    if (body.action === "impersonate") { window.location.href = "/"; return; }
    await load();
  }

  if (!data && !error) return <main className="min-h-screen bg-[#eef2f5] p-6 text-slate-600" dir={dir}>{text.loading}</main>;
  return <main className="min-h-screen bg-[#eef2f5] px-4 py-7 text-slate-900 sm:px-8" dir={dir}><div className="mx-auto max-w-7xl">
    <header className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-teal-700"><ShieldCheck className="h-4 w-4" />{text.eyebrow}</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">{text.title}</h1><p className="mt-2 text-sm text-slate-500">{text.intro}</p></div><button type="button" onClick={load} disabled={busy} className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-sm font-semibold shadow-sm hover:bg-slate-50 disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${busy ? "animate-spin" : ""}`} />{text.refresh}</button></header>
    {error && <div className="mb-5 flex items-center justify-between rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span>{error}</span><button type="button" onClick={() => setError(null)} aria-label={text.close}><X className="h-4 w-4" /></button></div>}
    {data && <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Building2} label={text.active} value={data.metrics.activeTenants} /><Metric icon={KeyRound} label={text.mrr} value={money(data.metrics.mrr, locale)} /><Metric icon={UserRound} label={text.users} value={data.metrics.totalUsers} /><Metric icon={CheckCircle2} label={text.health} value={text.healthy} good /></section><PlatformCommandCenter plans={data.plans} tenants={data.tenants} maintenance={data.maintenance} text={text} mutate={mutate} />
      <section className="mt-8 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">{text.tenants}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-start text-sm"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">{text.workspace}</th><th className="px-5 py-3">{text.admin}</th><th className="px-5 py-3">{text.plan}</th><th className="px-5 py-3">{text.limits}</th><th className="px-5 py-3">{text.created}</th><th className="px-5 py-3">{text.actions}</th></tr></thead><tbody className="divide-y divide-slate-100">{data.tenants.map((tenant) => <tr key={tenant.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-bold">{tenant.name}</td><td className="px-5 py-4 text-slate-500">{tenant.admin_email ?? "-"}</td><td className="px-5 py-4"><label className="sr-only" htmlFor={`plan-${tenant.id}`}>{text.changePlan}</label><select id={`plan-${tenant.id}`} value={tenant.plan_status} onChange={(event) => mutate({ action: "plan", tenantId: tenant.id, planStatus: event.target.value })} className={`rounded-md border-0 px-2.5 py-1 text-xs font-bold ${tenant.plan_status === "active" ? "bg-emerald-50 text-emerald-700" : tenant.plan_status === "suspended" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}><option value="trial">{text.trial}</option><option value="active">{text.activePlan}</option><option value="suspended">{text.suspended}</option></select></td><td className="px-5 py-4 text-slate-500">{tenant.user_count}/{tenant.max_users} · {tenant.max_warehouses}</td><td className="px-5 py-4 text-slate-500">{date(tenant.created_at, locale)}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-2"><button type="button" onClick={() => mutate({ action: "status", tenantId: tenant.id, status: tenant.status === "active" ? "suspended" : "active", planStatus: tenant.status === "active" ? "suspended" : "active" })} className="rounded-md border border-slate-200 px-2 py-1 text-xs font-semibold hover:bg-slate-100">{tenant.status === "active" ? text.suspend : text.unsuspend}</button><button type="button" onClick={() => setEditing(tenant)} aria-label={text.edit} className="rounded-md border border-slate-200 p-1.5 hover:bg-slate-100"><SlidersHorizontal className="h-3.5 w-3.5" /></button><button type="button" onClick={() => mutate({ action: "reset-password", tenantId: tenant.id })} aria-label={text.reset} className="rounded-md border border-slate-200 p-1.5 hover:bg-slate-100"><KeyRound className="h-3.5 w-3.5" /></button><button type="button" onClick={() => mutate({ action: "impersonate", tenantId: tenant.id })} aria-label={text.view} className="rounded-md border border-slate-200 p-1.5 hover:bg-slate-100"><Eye className="h-3.5 w-3.5" /></button></div></td></tr>)}</tbody></table></div></section>
      <section className="mt-8 rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">{text.audit}</p></div><div className="divide-y divide-slate-100">{data.auditLogs.length ? data.auditLogs.map((log) => <div key={log.id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-3 text-sm"><span className="font-semibold">{log.action}</span><span className="text-xs text-slate-500">{log.target_type} #{log.target_id ?? "-"} · {date(log.created_at, locale)}</span></div>) : <p className="px-5 py-6 text-sm text-slate-500">{text.noAudit}</p>}</div></section>
    </>}
    {editing && <LimitsDialog tenant={editing} text={text} onClose={() => setEditing(null)} onSave={async (maxUsers, maxWarehouses) => { await mutate({ action: "limits", tenantId: editing.id, maxUsers, maxWarehouses }); setEditing(null); }} />}
    {password && <div className="fixed inset-0 z-20 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-bold">{text.temporary}</h2><button type="button" onClick={() => setPassword(null)} aria-label={text.close}><X className="h-4 w-4" /></button></div><p className="mt-2 text-sm text-slate-500">{text.support}</p><div className="mt-5 flex gap-2"><code className="flex-1 rounded-lg bg-slate-100 px-3 py-3 text-sm font-bold">{password}</code><button type="button" onClick={() => navigator.clipboard.writeText(password)} className="rounded-lg bg-slate-950 px-3 text-xs font-bold text-white">{text.copy}</button></div></div></div>}
  </div></main>;
}

function Metric({ icon: Icon, label, value, good = false }: { icon: typeof Activity; label: string; value: string | number; good?: boolean }) { return <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between text-xs font-bold uppercase tracking-[0.12em] text-slate-400"><span>{label}</span><Icon className="h-4 w-4" /></div><p className={`mt-3 text-2xl font-bold ${good ? "text-emerald-700" : "text-slate-950"}`}>{value}</p></div>; }
function LimitsDialog({ tenant, text, onClose, onSave }: { tenant: Tenant; text: typeof copy.en; onClose: () => void; onSave: (users: number, warehouses: number) => Promise<void> }) { const [users, setUsers] = useState(String(tenant.max_users)); const [warehouses, setWarehouses] = useState(String(tenant.max_warehouses)); return <div className="fixed inset-0 z-20 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => { event.preventDefault(); onSave(Number(users), Number(warehouses)); }} className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-bold">{text.edit} · {tenant.name}</h2><button type="button" onClick={onClose} aria-label={text.close}><X className="h-4 w-4" /></button></div><label className="mt-5 block text-sm font-semibold">{text.limits.split(" /")[0]}<input required min="1" type="number" value={users} onChange={(event) => setUsers(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-200 px-3" /></label><label className="mt-4 block text-sm font-semibold">{text.limits.split(" /")[1]}<input required min="1" type="number" value={warehouses} onChange={(event) => setWarehouses(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-slate-200 px-3" /></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold">{text.cancel}</button><button type="submit" className="rounded-lg bg-slate-950 px-3 py-2 text-sm font-bold text-white">{text.save}</button></div></form></div>; }
