"use client";

import { useState } from "react";
import { Building2, Settings2, ShieldAlert, X } from "lucide-react";

type Plan = { id: string; name: string; monthly_price: number; feature_flags: Record<string, boolean> };
type Tenant = { id: number; name: string };
type Copy = {
  plans: string; operations: string; provision: string; maintenance: string; maintenanceOn: string; maintenanceOff: string;
  maintenanceHint: string; planFeatures: string; price: string; save: string; company: string; fullName: string;
  email: string; password: string; plan: string; cancel: string; provisionNow: string; promo: string; days: string;
  grant: string; close: string; free: string; pro: string; enterprise: string; note: string;
};

type Props = { plans: Plan[]; tenants: Tenant[]; maintenance: boolean; text: Copy; mutate: (body: Record<string, unknown>) => Promise<void>; };

export default function PlatformCommandCenter({ plans, tenants, maintenance, text, mutate }: Props) {
  const [tab, setTab] = useState<"operations" | "plans">("operations");
  const [provisionOpen, setProvisionOpen] = useState(false);
  const [promoTenant, setPromoTenant] = useState<Tenant | null>(null);
  const [planDrafts, setPlanDrafts] = useState<Record<string, Plan>>(() => Object.fromEntries(plans.map((plan) => [plan.id, plan])));

  return <section className="mt-8 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4">
      <div className="flex gap-2"><button type="button" onClick={() => setTab("operations")} className={`rounded-lg px-3 py-2 text-sm font-bold ${tab === "operations" ? "bg-slate-950 text-white" : "text-slate-500 hover:bg-slate-100"}`}><Settings2 className="me-2 inline h-4 w-4" />{text.operations}</button><button type="button" onClick={() => setTab("plans")} className={`rounded-lg px-3 py-2 text-sm font-bold ${tab === "plans" ? "bg-slate-950 text-white" : "text-slate-500 hover:bg-slate-100"}`}>{text.plans}</button></div>
      {tab === "operations" && <div className="flex gap-2"><button type="button" onClick={() => setProvisionOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-teal-700 px-3 py-2 text-xs font-bold text-white hover:bg-teal-800"><Building2 className="h-4 w-4" />{text.provision}</button><button type="button" onClick={() => mutate({ action: "maintenance", enabled: !maintenance })} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${maintenance ? "bg-amber-100 text-amber-800" : "border border-slate-200 text-slate-700 hover:bg-slate-50"}`}><ShieldAlert className="h-4 w-4" />{maintenance ? text.maintenanceOff : text.maintenanceOn}</button></div>}
    </div>
    {tab === "operations" ? <div className="grid gap-4 p-5 md:grid-cols-2"><div className="rounded-lg bg-slate-50 p-4"><p className="text-sm font-bold text-slate-900">{text.maintenance}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text.maintenanceHint}</p><p className={`mt-3 text-xs font-bold ${maintenance ? "text-amber-700" : "text-emerald-700"}`}>{maintenance ? text.maintenanceOn : text.maintenanceOff}</p></div><div className="rounded-lg bg-slate-50 p-4"><p className="text-sm font-bold text-slate-900">{text.promo}</p><div className="mt-3 flex gap-2"><select aria-label={text.company} className="h-9 min-w-0 flex-1 rounded-md border border-slate-200 bg-white px-2 text-xs" onChange={(event) => setPromoTenant(tenants.find((tenant) => String(tenant.id) === event.target.value) ?? null)} defaultValue=""><option value="">{text.company}</option>{tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.name}</option>)}</select>{promoTenant && <button type="button" onClick={() => setPromoTenant(promoTenant)} className="rounded-md bg-slate-950 px-3 text-xs font-bold text-white">{text.grant}</button>}</div></div></div> : <div className="grid gap-4 p-5 lg:grid-cols-3">{plans.map((plan) => { const draft = planDrafts[plan.id] ?? plan; return <div key={plan.id} className="rounded-lg border border-slate-200 p-4"><div className="flex items-center justify-between"><h3 className="font-bold">{plan.name}</h3><span className="text-sm font-bold">${draft.monthly_price}</span></div><label className="mt-4 block text-xs font-semibold text-slate-500">{text.price}<input type="number" min="0" value={draft.monthly_price} onChange={(event) => setPlanDrafts((current) => ({ ...current, [plan.id]: { ...draft, monthly_price: Number(event.target.value) } }))} className="mt-1 h-9 w-full rounded-md border border-slate-200 px-2" /></label><p className="mt-4 text-xs font-bold text-slate-500">{text.planFeatures}</p><div className="mt-2 space-y-2">{Object.entries(draft.feature_flags ?? {}).map(([feature, enabled]) => <label key={feature} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={Boolean(enabled)} onChange={(event) => setPlanDrafts((current) => ({ ...current, [plan.id]: { ...draft, feature_flags: { ...draft.feature_flags, [feature]: event.target.checked } } }))} />{feature}</label>)}</div><button type="button" onClick={() => mutate({ action: "plan-config", planId: plan.id, monthlyPrice: draft.monthly_price, featureFlags: draft.feature_flags })} className="mt-4 rounded-md bg-slate-950 px-3 py-2 text-xs font-bold text-white">{text.save}</button></div>; })}</div>}
    {provisionOpen && <ProvisionDialog text={text} onClose={() => setProvisionOpen(false)} onSave={async (body) => { await mutate({ action: "provision", ...body }); setProvisionOpen(false); }} />}
    {promoTenant && <PromoDialog tenant={promoTenant} text={text} onClose={() => setPromoTenant(null)} onSave={async (days, note) => { await mutate({ action: "promo", tenantId: promoTenant.id, extensionDays: days, note }); setPromoTenant(null); }} />}
  </section>;
}

function ProvisionDialog({ text, onClose, onSave }: { text: Copy; onClose: () => void; onSave: (body: Record<string, unknown>) => Promise<void> }) { const [form, setForm] = useState({ companyName: "", adminFullName: "", email: "", password: "", subscriptionPlan: "free" }); const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value })); return <div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => { event.preventDefault(); onSave(form); }} className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-bold">{text.provision}</h2><button type="button" onClick={onClose} aria-label={text.close}><X className="h-4 w-4" /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["companyName", text.company], ["adminFullName", text.fullName], ["email", text.email], ["password", text.password]].map(([key, label]) => <label key={key} className="text-xs font-semibold">{label}<input required type={key === "password" ? "password" : key === "email" ? "email" : "text"} value={form[key as keyof typeof form]} onChange={(event) => update(key, event.target.value)} className="mt-1 h-10 w-full rounded-md border border-slate-200 px-3" /></label>)}<label className="text-xs font-semibold">{text.plan}<select value={form.subscriptionPlan} onChange={(event) => update("subscriptionPlan", event.target.value)} className="mt-1 h-10 w-full rounded-md border border-slate-200 px-3"><option value="free">{text.free}</option><option value="pro">{text.pro}</option><option value="enterprise">{text.enterprise}</option></select></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-md border border-slate-200 px-3 py-2 text-sm font-semibold">{text.cancel}</button><button type="submit" className="rounded-md bg-slate-950 px-3 py-2 text-sm font-bold text-white">{text.provisionNow}</button></div></form></div>; }
function PromoDialog({ tenant, text, onClose, onSave }: { tenant: Tenant; text: Copy; onClose: () => void; onSave: (days: number, note: string) => Promise<void> }) { const [days, setDays] = useState("30"); const [note, setNote] = useState(""); return <div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => { event.preventDefault(); onSave(Number(days), note); }} className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-bold">{text.promo} · {tenant.name}</h2><button type="button" onClick={onClose} aria-label={text.close}><X className="h-4 w-4" /></button></div><label className="mt-5 block text-sm font-semibold">{text.days}<input required min="1" type="number" value={days} onChange={(event) => setDays(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-slate-200 px-3" /></label><label className="mt-4 block text-sm font-semibold">{text.note}<input type="text" value={note} onChange={(event) => setNote(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-slate-200 px-3" /></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-md border border-slate-200 px-3 py-2 text-sm font-semibold">{text.cancel}</button><button type="submit" className="rounded-md bg-slate-950 px-3 py-2 text-sm font-bold text-white">{text.grant}</button></div></form></div>; }
