"use client";

import { useEffect, useState } from "react";
import { Database, Gauge, Search, ShieldCheck, Users, Wrench } from "lucide-react";

type Tenant = { id: number; name: string };
type User = { user_id: string; tenant_id: number; email: string | null; username: string | null; role: string; is_active: boolean };
type Props = { tenants: Tenant[]; maintenance: boolean; onMaintenanceChange: (enabled: boolean) => Promise<void> };
const tabs = [{ id: "tenants", label: "Workspaces & Tenants", icon: Gauge }, { id: "users", label: "Global Users & Roles", icon: Users }, { id: "tables", label: "Data & Tables Inspector", icon: Database }, { id: "infra", label: "Platform & Infrastructure", icon: Wrench }] as const;
type Tab = typeof tabs[number]["id"];

export default function SuperAdminGovernance({ tenants, maintenance, onMaintenanceChange }: Props) {
  const [tab, setTab] = useState<Tab>("tenants");
  const [users, setUsers] = useState<User[]>([]);
  const [search, setSearch] = useState("");
  const [table, setTable] = useState("products");
  const [rows, setRows] = useState<Record<string, unknown>[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [jsonValues, setJsonValues] = useState("{}");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => { if (tab === "users") fetch(`/api/super-admin/users?search=${encodeURIComponent(search)}`).then((response) => response.json()).then((body) => setUsers(body.users ?? [])).catch(() => setMessage("Unable to load users.")); }, [tab, search]);
  useEffect(() => { if (tab === "tables") fetch(`/api/super-admin/tables?table=${table}`).then((response) => response.json()).then((body) => setRows(body.rows ?? [])).catch(() => setMessage("Unable to load table data.")); }, [tab, table]);

  async function userAction(body: Record<string, unknown>) {
    setBusy(true); setMessage("");
    const response = await fetch("/api/super-admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json().catch(() => null) as { error?: string; temporaryPassword?: string } | null;
    setMessage(result?.temporaryPassword ? `Temporary password: ${result.temporaryPassword}` : result?.error ?? (response.ok ? "User updated." : "Update failed."));
    setBusy(false);
    if (response.ok) setUsers((current) => current.map((user) => user.user_id === body.userId ? { ...user, ...(body.action === "role" ? { role: body.role as string } : {}), ...(body.action === "ban" || body.action === "unban" ? { is_active: body.action === "unban" } : {}), ...(body.action === "assign-tenant" ? { tenant_id: body.tenantId as number } : {}) } : user));
  }

  return <section className="mt-8 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto border-b border-slate-100"><div className="flex min-w-max gap-1 p-2">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => { setTab(id); setMessage(""); }} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm font-bold ${tab === id ? "bg-slate-950 text-white" : "text-slate-500 hover:bg-slate-100"}`}><Icon className="h-4 w-4" />{label}</button>)}</div></div>{message && <p className="border-b border-blue-100 bg-blue-50 px-5 py-3 text-sm font-semibold text-blue-800">{message}</p>}
    {tab === "tenants" && <div className="grid gap-4 p-5 md:grid-cols-2"><div><h2 className="text-lg font-bold">Workspace governance</h2><p className="mt-1 text-sm leading-6 text-slate-500">Tenant controls, limits, ownership, and subscription actions are available in the organization table below.</p></div><div className="rounded-lg bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Scope</p><p className="mt-2 text-2xl font-bold">{tenants.length}</p><p className="text-sm text-slate-500">workspaces under platform control</p></div></div>}
    {tab === "users" && <div className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Every user, one control surface</h2><p className="mt-1 text-sm text-slate-500">Search identities across every tenant and apply governed access actions.</p></div><label className="flex h-10 w-full items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm sm:w-64"><Search className="h-4 w-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search users" className="min-w-0 flex-1 outline-none" /></label></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[780px] text-start text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-3 py-3">Identity</th><th className="px-3 py-3">Tenant</th><th className="px-3 py-3">Role</th><th className="px-3 py-3">State</th><th className="px-3 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{users.map((user) => <tr key={user.user_id}><td className="px-3 py-3 font-semibold">{user.email ?? user.username ?? user.user_id}</td><td className="px-3 py-3 text-slate-500">{tenants.find((tenant) => tenant.id === user.tenant_id)?.name ?? `#${user.tenant_id}`}</td><td className="px-3 py-3"><select value={user.role} onChange={(event) => userAction({ action: "role", userId: user.user_id, role: event.target.value })} className="rounded border border-slate-200 px-2 py-1 text-xs"><option value="owner">Owner</option><option value="manager">Manager</option><option value="warehouse_worker">Warehouse</option><option value="cashier">Cashier</option></select></td><td className={`px-3 py-3 font-semibold ${user.is_active ? "text-emerald-700" : "text-red-700"}`}>{user.is_active ? "Active" : "Banned"}</td><td className="px-3 py-3"><div className="flex gap-2"><button disabled={busy} type="button" onClick={() => userAction({ action: user.is_active ? "ban" : "unban", userId: user.user_id })} className="rounded border border-slate-200 px-2 py-1 text-xs font-semibold">{user.is_active ? "Ban" : "Unban"}</button><button disabled={busy} type="button" onClick={() => userAction({ action: "reset-password", userId: user.user_id })} className="rounded bg-slate-950 px-2 py-1 text-xs font-semibold text-white">Reset</button></div></td></tr>)}</tbody></table></div></div>}
    {tab === "tables" && <div className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Global data browser</h2><p className="mt-1 text-sm text-slate-500">Service-role CRUD access for critical platform tables. Writes are audited through the API.</p></div><select value={table} onChange={(event) => setTable(event.target.value)} className="h-10 rounded-lg border border-slate-200 px-3 text-sm font-semibold"><option value="products">Products</option><option value="invoices">Invoices</option><option value="warehouses">Warehouses</option><option value="system_audit_logs">Audit logs</option></select></div><div className="mt-5 grid gap-4 lg:grid-cols-[1fr_300px]"><pre className="max-h-80 overflow-auto rounded-lg bg-slate-950 p-4 text-xs leading-5 text-emerald-300">{JSON.stringify(rows, null, 2)}</pre><div><label className="text-xs font-semibold">Row ID<input value={selectedId} onChange={(event) => setSelectedId(event.target.value)} className="mt-1 h-9 w-full rounded border border-slate-200 px-2" /></label><label className="mt-3 block text-xs font-semibold">JSON values<textarea value={jsonValues} onChange={(event) => setJsonValues(event.target.value)} className="mt-1 h-32 w-full rounded border border-slate-200 p-2 font-mono text-xs" /></label><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={async () => { const response = await fetch("/api/super-admin/tables", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ table, values: JSON.parse(jsonValues) }) }); setMessage(response.ok ? "Row created." : "Create failed."); }} className="rounded bg-slate-950 px-3 py-2 text-xs font-bold text-white">Create</button><button type="button" onClick={async () => { const response = await fetch("/api/super-admin/tables", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ table, id: selectedId, values: JSON.parse(jsonValues) }) }); setMessage(response.ok ? "Row updated." : "Update failed."); }} className="rounded border border-slate-200 px-3 py-2 text-xs font-bold">Update</button><button type="button" onClick={async () => { const response = await fetch("/api/super-admin/tables", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ table, id: selectedId }) }); setMessage(response.ok ? "Row deleted." : "Delete failed."); }} className="rounded border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Delete</button></div></div></div></div>}
    {tab === "infra" && <div className="grid gap-4 p-5 md:grid-cols-2"><div><h2 className="text-lg font-bold">Infrastructure controls</h2><p className="mt-1 text-sm leading-6 text-slate-500">Protect migrations and incident response with explicit platform-wide controls.</p><button type="button" onClick={() => onMaintenanceChange(!maintenance)} className={`mt-5 inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-bold ${maintenance ? "bg-amber-100 text-amber-900" : "bg-slate-950 text-white"}`}><ShieldCheck className="h-4 w-4" />{maintenance ? "Disable maintenance mode" : "Enable maintenance mode"}</button></div><div className="rounded-lg border border-slate-200 p-4"><div className="flex items-center gap-2 text-sm font-bold"><span className="h-2 w-2 rounded-full bg-emerald-500" />Database operational</div><div className="mt-3 flex items-center gap-2 text-sm font-bold"><span className="h-2 w-2 rounded-full bg-emerald-500" />Authentication operational</div><button type="button" onClick={async () => { const response = await fetch("/api/super-admin/infrastructure", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "flush-cache" }) }); setMessage(response.ok ? "Redis cache flushed." : (await response.json()).error ?? "Cache flush failed."); }} className="mt-5 rounded-lg border border-slate-200 px-3 py-2 text-sm font-bold">Flush Redis cache</button></div></div>}
  </section>;
}
