-- StoreFlow 003: accounting, receivables, returns, and inventory controls.
-- Run after 002_enterprise_offline.sql. All monetary values use numeric(14,2).

CREATE TABLE IF NOT EXISTS customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text,
  email text,
  credit_limit numeric(14,2) NOT NULL DEFAULT 0 CHECK (credit_limit >= 0),
  opening_balance numeric(14,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_customers_store_name ON customers(store_id, name);

CREATE TABLE IF NOT EXISTS chart_of_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  code text NOT NULL,
  name text NOT NULL,
  account_type text NOT NULL CHECK (account_type IN ('asset','liability','equity','revenue','expense')),
  parent_id bigint REFERENCES chart_of_accounts(id),
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(store_id, code)
);

CREATE TABLE IF NOT EXISTS journal_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  entry_date timestamptz NOT NULL DEFAULT now(),
  reference_type text NOT NULL,
  reference_id bigint,
  memo text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS journal_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_entry_id bigint NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
  account_id bigint NOT NULL REFERENCES chart_of_accounts(id),
  debit numeric(14,2) NOT NULL DEFAULT 0 CHECK (debit >= 0),
  credit numeric(14,2) NOT NULL DEFAULT 0 CHECK (credit >= 0),
  description text,
  CHECK ((debit = 0 AND credit > 0) OR (credit = 0 AND debit > 0))
);
CREATE INDEX IF NOT EXISTS idx_journal_entries_store_date ON journal_entries(store_id, entry_date DESC);

CREATE TABLE IF NOT EXISTS invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  customer_id bigint REFERENCES customers(id) ON DELETE SET NULL,
  invoice_number text NOT NULL,
  invoice_type text NOT NULL DEFAULT 'cash' CHECK (invoice_type IN ('cash','credit','proforma','credit_note')),
  status text NOT NULL DEFAULT 'issued' CHECK (status IN ('draft','issued','partially_paid','paid','void')),
  subtotal numeric(14,2) NOT NULL DEFAULT 0,
  discount numeric(14,2) NOT NULL DEFAULT 0,
  tax numeric(14,2) NOT NULL DEFAULT 0,
  total numeric(14,2) NOT NULL DEFAULT 0,
  paid numeric(14,2) NOT NULL DEFAULT 0,
  due_date date,
  issued_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(store_id, invoice_number)
);
CREATE TABLE IF NOT EXISTS invoice_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  product_id bigint REFERENCES products(id) ON DELETE SET NULL,
  description text NOT NULL,
  quantity numeric(14,3) NOT NULL CHECK (quantity > 0),
  unit_price numeric(14,2) NOT NULL DEFAULT 0,
  unit_cost numeric(14,2) NOT NULL DEFAULT 0,
  line_total numeric(14,2) NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  customer_id bigint REFERENCES customers(id) ON DELETE SET NULL,
  invoice_id bigint REFERENCES invoices(id) ON DELETE SET NULL,
  amount numeric(14,2) NOT NULL CHECK (amount > 0),
  payment_method text NOT NULL DEFAULT 'cash',
  paid_at timestamptz NOT NULL DEFAULT now(),
  note text
);

ALTER TABLE products ADD COLUMN IF NOT EXISTS cost numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_rate numeric(5,2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS reorder_point integer NOT NULL DEFAULT 5;
ALTER TABLE products ADD COLUMN IF NOT EXISTS track_serial boolean NOT NULL DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS track_batch boolean NOT NULL DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_composite boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS inventory_lots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  warehouse_id bigint NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  lot_number text NOT NULL,
  serial_number text,
  expires_at date,
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  UNIQUE(warehouse_id, product_id, lot_number, serial_number)
);
CREATE INDEX IF NOT EXISTS idx_inventory_lots_expiry ON inventory_lots(store_id, expires_at);

CREATE TABLE IF NOT EXISTS product_bom_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  parent_product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  component_product_id bigint NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity numeric(14,3) NOT NULL CHECK (quantity > 0),
  UNIQUE(parent_product_id, component_product_id)
);

CREATE TABLE IF NOT EXISTS returns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  invoice_id bigint REFERENCES invoices(id) ON DELETE SET NULL,
  customer_id bigint REFERENCES customers(id) ON DELETE SET NULL,
  reason text,
  total numeric(14,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS return_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id bigint NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id),
  warehouse_id bigint NOT NULL REFERENCES warehouses(id),
  quantity numeric(14,3) NOT NULL CHECK (quantity > 0),
  unit_price numeric(14,2) NOT NULL DEFAULT 0
);

INSERT INTO chart_of_accounts(store_id, code, name, account_type, is_system)
VALUES
  (1, '1000', 'Cash', 'asset', true),
  (1, '1100', 'Accounts Receivable', 'asset', true),
  (1, '1200', 'Inventory', 'asset', true),
  (1, '2000', 'Accounts Payable', 'liability', true),
  (1, '3000', 'Owner Equity', 'equity', true),
  (1, '4000', 'Sales Revenue', 'revenue', true),
  (1, '5000', 'Cost of Goods Sold', 'expense', true)
ON CONFLICT (store_id, code) DO NOTHING;

CREATE OR REPLACE VIEW financial_account_balances AS
SELECT ca.store_id, ca.id, ca.code, ca.name, ca.account_type,
       COALESCE(SUM(jl.debit - jl.credit), 0)::numeric(14,2) AS balance
FROM chart_of_accounts ca
LEFT JOIN journal_lines jl ON jl.account_id = ca.id
GROUP BY ca.store_id, ca.id, ca.code, ca.name, ca.account_type;
