-- StoreFlow 004: canonical multi-tenant WMS contract.
-- Compatibility migration: existing store_id columns remain available while
-- tenant_id becomes the indexed isolation key for new handlers.

CREATE TABLE IF NOT EXISTS tenants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO tenants (id, name, slug)
VALUES (1, 'Main Store', 'main-store')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE stores ADD COLUMN IF NOT EXISTS tenant_id bigint REFERENCES tenants(id);
UPDATE stores SET tenant_id = id WHERE tenant_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_stores_tenant_id ON stores(tenant_id);

ALTER TABLE products ADD COLUMN IF NOT EXISTS tenant_id bigint REFERENCES tenants(id);
UPDATE products SET tenant_id = store_id WHERE tenant_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_products_tenant_sku ON products(tenant_id, name, id);

ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS tenant_id bigint REFERENCES tenants(id);
UPDATE warehouses SET tenant_id = store_id WHERE tenant_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_warehouses_tenant_id ON warehouses(tenant_id, id);

CREATE TABLE IF NOT EXISTS entities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  entity_type text NOT NULL CHECK (entity_type IN ('customer', 'supplier', 'employee')),
  display_name text NOT NULL,
  phone text,
  email text,
  credit_limit numeric(14,2) NOT NULL DEFAULT 0 CHECK (credit_limit >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_entities_tenant_type_name ON entities(tenant_id, entity_type, display_name);

CREATE TABLE IF NOT EXISTS tenant_memberships (
  tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role IN ('super_admin', 'manager', 'warehouse_worker')),
  warehouse_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_tenant_memberships_user ON tenant_memberships(user_id, tenant_id);

CREATE TABLE IF NOT EXISTS inventory_stock (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  warehouse_id bigint NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  sku text,
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  reorder_point integer NOT NULL DEFAULT 5 CHECK (reorder_point >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(tenant_id, warehouse_id, product_id)
);
CREATE INDEX IF NOT EXISTS idx_inventory_stock_tenant_warehouse_sku ON inventory_stock(tenant_id, warehouse_id, sku);

INSERT INTO inventory_stock(tenant_id, warehouse_id, product_id, sku, quantity, reorder_point)
SELECT w.tenant_id, i.warehouse_id, i.product_id, p.name, i.quantity, i.reorder_point
FROM inventory i
JOIN warehouses w ON w.id = i.warehouse_id
JOIN products p ON p.id = i.product_id
ON CONFLICT (tenant_id, warehouse_id, product_id) DO UPDATE SET
  quantity = EXCLUDED.quantity,
  reorder_point = EXCLUDED.reorder_point,
  sku = EXCLUDED.sku;

CREATE TABLE IF NOT EXISTS stock_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  warehouse_id bigint REFERENCES warehouses(id) ON DELETE SET NULL,
  product_id bigint REFERENCES products(id) ON DELETE SET NULL,
  movement_type text NOT NULL CHECK (movement_type IN ('sale', 'purchase', 'transfer_in', 'transfer_out', 'adjustment', 'return', 'assembly')),
  quantity integer NOT NULL,
  reference_type text,
  reference_id bigint,
  idempotency_key text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_stock_ledger_tenant_created ON stock_ledger(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_ledger_tenant_warehouse_product ON stock_ledger(tenant_id, warehouse_id, product_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_stock_ledger_tenant_idempotency ON stock_ledger(tenant_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tenant_id bigint REFERENCES tenants(id);
UPDATE invoices SET tenant_id = store_id WHERE tenant_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_invoices_tenant_status_date ON invoices(tenant_id, status, issued_at DESC);

ALTER TABLE invoice_lines ADD COLUMN IF NOT EXISTS tenant_id bigint REFERENCES tenants(id);
UPDATE invoice_lines SET tenant_id = (SELECT tenant_id FROM invoices WHERE invoices.id = invoice_lines.invoice_id) WHERE tenant_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_invoice_lines_tenant_invoice ON invoice_lines(tenant_id, invoice_id);

ALTER TABLE sales ADD COLUMN IF NOT EXISTS tenant_id bigint REFERENCES tenants(id);
UPDATE sales SET tenant_id = store_id WHERE tenant_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_sales_tenant_date ON sales(tenant_id, sold_at DESC);

-- RLS is deny-by-default. The application must use Supabase Auth JWTs with
-- tenant_memberships rows; warehouse workers are restricted to their assigned
-- warehouse while managers and super-admins can access the full tenant.
CREATE OR REPLACE FUNCTION app_tenant_id() RETURNS bigint AS $$
  SELECT NULLIF((auth.jwt() ->> 'tenant_id'), '')::bigint;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION can_access_tenant(target_tenant_id bigint)
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM tenant_memberships m
    WHERE m.tenant_id = target_tenant_id
      AND m.user_id = auth.uid()
  );
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION can_access_warehouse(target_tenant_id bigint, target_warehouse_id bigint)
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM tenant_memberships m
    WHERE m.tenant_id = target_tenant_id
      AND m.user_id = auth.uid()
      AND (m.role IN ('super_admin', 'manager') OR m.warehouse_id = target_warehouse_id)
  );
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;

ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_self_access ON tenants;
CREATE POLICY tenant_self_access ON tenants FOR SELECT USING (can_access_tenant(id));
DROP POLICY IF EXISTS membership_self_access ON tenant_memberships;
CREATE POLICY membership_self_access ON tenant_memberships FOR SELECT USING (user_id = auth.uid() OR can_access_tenant(tenant_id));
DROP POLICY IF EXISTS entities_tenant_access ON entities;
CREATE POLICY entities_tenant_access ON entities USING (can_access_tenant(tenant_id)) WITH CHECK (can_access_tenant(tenant_id));
DROP POLICY IF EXISTS inventory_stock_warehouse_access ON inventory_stock;
CREATE POLICY inventory_stock_warehouse_access ON inventory_stock USING (can_access_warehouse(tenant_id, warehouse_id)) WITH CHECK (can_access_warehouse(tenant_id, warehouse_id));
DROP POLICY IF EXISTS stock_ledger_warehouse_access ON stock_ledger;
CREATE POLICY stock_ledger_warehouse_access ON stock_ledger USING (can_access_warehouse(tenant_id, warehouse_id)) WITH CHECK (can_access_warehouse(tenant_id, warehouse_id));
DROP POLICY IF EXISTS invoices_tenant_access ON invoices;
CREATE POLICY invoices_tenant_access ON invoices USING (can_access_tenant(tenant_id)) WITH CHECK (can_access_tenant(tenant_id));
DROP POLICY IF EXISTS invoice_lines_tenant_access ON invoice_lines;
CREATE POLICY invoice_lines_tenant_access ON invoice_lines USING (can_access_tenant(tenant_id)) WITH CHECK (can_access_tenant(tenant_id));
DROP POLICY IF EXISTS sales_tenant_access ON sales;
CREATE POLICY sales_tenant_access ON sales USING (can_access_tenant(tenant_id)) WITH CHECK (can_access_tenant(tenant_id));
