-- StoreFlow 005: tenant onboarding, trial lifecycle, and activation vouchers.
-- The provisioning function is SECURITY DEFINER and should only be executable
-- by the service role from the server-side registration endpoint.

ALTER TABLE tenants ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS subscription_expires_at timestamptz NOT NULL DEFAULT (now() + interval '30 days');
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE tenants DROP CONSTRAINT IF EXISTS tenants_status_check;
ALTER TABLE tenants ADD CONSTRAINT tenants_status_check CHECK (status IN ('active', 'suspended'));

ALTER TABLE tenant_memberships DROP CONSTRAINT IF EXISTS tenant_memberships_role_check;
ALTER TABLE tenant_memberships ADD CONSTRAINT tenant_memberships_role_check CHECK (role IN ('owner', 'super_admin', 'manager', 'warehouse_worker'));

CREATE TABLE IF NOT EXISTS activation_vouchers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  months integer NOT NULL CHECK (months > 0 AND months <= 120),
  redeemed_by_tenant_id bigint REFERENCES tenants(id) ON DELETE SET NULL,
  redeemed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_activation_vouchers_available ON activation_vouchers(code) WHERE redeemed_at IS NULL;

CREATE TABLE IF NOT EXISTS system_admins (
  user_id uuid PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION provision_tenant(
  company_name text,
  owner_user_id uuid,
  activation_code text DEFAULT NULL
) RETURNS bigint AS $$
DECLARE
  new_tenant_id bigint;
  new_warehouse_id bigint;
  extension_months integer := 0;
BEGIN
  IF trim(company_name) = '' OR owner_user_id IS NULL THEN
    RAISE EXCEPTION 'Company name and owner are required';
  END IF;

  IF activation_code IS NOT NULL AND trim(activation_code) <> '' THEN
    SELECT months INTO extension_months FROM activation_vouchers
    WHERE code = upper(trim(activation_code)) AND redeemed_at IS NULL
    FOR UPDATE;
    IF extension_months IS NULL THEN
      RAISE EXCEPTION 'Activation code is invalid or already used';
    END IF;
  END IF;

  INSERT INTO tenants(name, slug, status, subscription_expires_at, created_by)
  VALUES (
    trim(company_name),
    regexp_replace(lower(trim(company_name)) || '-' || substr(md5(random()::text), 1, 8), '[^a-z0-9-]', '-', 'g'),
    'active',
    now() + interval '30 days' + (extension_months * interval '1 month'),
    owner_user_id
  ) RETURNING id INTO new_tenant_id;

  INSERT INTO tenant_memberships(tenant_id, user_id, role)
  VALUES (new_tenant_id, owner_user_id, 'owner');

  INSERT INTO stores(id, name, tenant_id)
  VALUES (new_tenant_id, trim(company_name), new_tenant_id);

  INSERT INTO warehouses(tenant_id, store_id, name, location, is_main)
  VALUES (new_tenant_id, new_tenant_id, 'المستودع الرئيسي (Main Warehouse)', 'Default', true)
  RETURNING id INTO new_warehouse_id;

  IF extension_months > 0 THEN
    UPDATE activation_vouchers SET redeemed_by_tenant_id = new_tenant_id, redeemed_at = now()
    WHERE code = upper(trim(activation_code));
  END IF;
  RETURN new_tenant_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION provision_tenant(text, uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION provision_tenant(text, uuid, text) TO service_role;
