-- StoreFlow 006: tenant currencies, inventory valuation layers, and role policy.

ALTER TABLE tenants ADD COLUMN IF NOT EXISTS base_currency text NOT NULL DEFAULT 'USD'
  CHECK (base_currency IN ('USD', 'ILS', 'JOD'));
ALTER TABLE products ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'USD'
  CHECK (currency IN ('USD', 'ILS', 'JOD'));
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'USD'
  CHECK (currency IN ('USD', 'ILS', 'JOD'));
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS exchange_rate numeric(18,8) NOT NULL DEFAULT 1;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS total_base numeric(14,2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'USD'
  CHECK (currency IN ('USD', 'ILS', 'JOD'));
ALTER TABLE sales ADD COLUMN IF NOT EXISTS exchange_rate numeric(18,8) NOT NULL DEFAULT 1;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS total_base numeric(14,2) NOT NULL DEFAULT 0;

ALTER TABLE tenant_memberships DROP CONSTRAINT IF EXISTS tenant_memberships_role_check;
ALTER TABLE tenant_memberships ADD CONSTRAINT tenant_memberships_role_check
  CHECK (role IN ('owner', 'warehouse_manager', 'cashier', 'accountant'));

CREATE TABLE IF NOT EXISTS inventory_cost_layers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  warehouse_id bigint NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  received_at timestamptz NOT NULL DEFAULT now(),
  quantity numeric(14,3) NOT NULL CHECK (quantity >= 0),
  remaining_quantity numeric(14,3) NOT NULL CHECK (remaining_quantity >= 0),
  unit_cost numeric(14,2) NOT NULL CHECK (unit_cost >= 0),
  currency text NOT NULL DEFAULT 'USD' CHECK (currency IN ('USD', 'ILS', 'JOD'))
);
CREATE INDEX IF NOT EXISTS idx_inventory_cost_layers_fifo
  ON inventory_cost_layers(tenant_id, warehouse_id, product_id, received_at, id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant_user_created
  ON audit_logs(store_id, user_id, created_at DESC);