-- Server-managed credentials. Password/PIN hashes are never exposed to clients.
CREATE TABLE IF NOT EXISTS tenant_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  warehouse_id bigint REFERENCES warehouses(id) ON DELETE SET NULL,
  role text NOT NULL CHECK (role IN ('owner', 'super_admin', 'manager', 'warehouse_worker', 'cashier')),
  username text,
  phone text,
  email text NOT NULL,
  identifier_normalized text NOT NULL UNIQUE,
  password_hash text,
  pin_hash text,
  allowed_warehouses bigint[] NOT NULL DEFAULT '{}',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (password_hash IS NOT NULL OR pin_hash IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_tenant_users_tenant ON tenant_users(tenant_id);
ALTER TABLE tenant_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_users_self_access ON tenant_users;
CREATE POLICY tenant_users_self_access ON tenant_users FOR SELECT USING (
  user_id = auth.uid() AND tenant_id = app_tenant_id()
);
REVOKE ALL ON tenant_users FROM anon, authenticated;
GRANT SELECT ON tenant_users TO service_role;

-- These helpers make application claims available to every tenant policy.
CREATE OR REPLACE FUNCTION app_warehouse_id() RETURNS bigint AS $$
  SELECT NULLIF((auth.jwt() ->> 'warehouse_id'), '')::bigint;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION app_role() RETURNS text AS $$
  SELECT NULLIF(auth.jwt() ->> 'role', '');
$$ LANGUAGE sql STABLE;