-- StoreFlow 008: system super-admin control plane.
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS plan_status text NOT NULL DEFAULT 'trial';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS max_users integer NOT NULL DEFAULT 25 CHECK (max_users > 0);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS max_warehouses integer NOT NULL DEFAULT 1 CHECK (max_warehouses > 0);
ALTER TABLE tenants DROP CONSTRAINT IF EXISTS tenants_plan_status_check;
ALTER TABLE tenants ADD CONSTRAINT tenants_plan_status_check CHECK (plan_status IN ('trial', 'active', 'suspended'));

ALTER TABLE tenant_users DROP CONSTRAINT IF EXISTS tenant_users_role_check;
ALTER TABLE tenant_users ADD CONSTRAINT tenant_users_role_check CHECK (role IN ('owner', 'super_admin', 'SUPER_ADMIN', 'manager', 'warehouse_worker', 'cashier', 'accountant'));

CREATE TABLE IF NOT EXISTS system_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  target_type text NOT NULL,
  target_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_system_audit_logs_created ON system_audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_audit_logs_target ON system_audit_logs(target_type, target_id);
ALTER TABLE system_audit_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON system_audit_logs FROM anon, authenticated;
GRANT ALL ON system_audit_logs TO service_role;

CREATE OR REPLACE FUNCTION is_system_super_admin(target_user_id uuid)
RETURNS boolean AS $$
  SELECT EXISTS (SELECT 1 FROM system_admins WHERE user_id = target_user_id);
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;