-- StoreFlow 010: command-center controls for plans, maintenance, and promotions.
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS subscription_plan text NOT NULL DEFAULT 'free';
ALTER TABLE tenants DROP CONSTRAINT IF EXISTS tenants_subscription_plan_check;
ALTER TABLE tenants ADD CONSTRAINT tenants_subscription_plan_check CHECK (subscription_plan IN ('free', 'pro', 'enterprise'));

CREATE TABLE IF NOT EXISTS platform_plans (
  id text PRIMARY KEY,
  name text NOT NULL,
  monthly_price numeric(12, 2) NOT NULL DEFAULT 0 CHECK (monthly_price >= 0),
  feature_flags jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO platform_plans (id, name, monthly_price, feature_flags) VALUES
  ('free', 'Free', 0, '{"analytics": false, "exports": false, "ai": false}'),
  ('pro', 'Pro', 99, '{"analytics": true, "exports": true, "ai": true}'),
  ('enterprise', 'Enterprise', 299, '{"analytics": true, "exports": true, "ai": true, "sso": true}')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS tenant_promotions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  extension_days integer NOT NULL CHECK (extension_days > 0),
  expires_at timestamptz NOT NULL,
  note text,
  granted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS platform_settings (
  id integer PRIMARY KEY CHECK (id = 1),
  maintenance_mode boolean NOT NULL DEFAULT false,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO platform_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
ALTER TABLE platform_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON platform_plans, tenant_promotions, platform_settings FROM anon, authenticated;
GRANT ALL ON platform_plans, tenant_promotions, platform_settings TO service_role;